import:
  - ~/.config/alacritty/themes/tokyo-night.yaml

font:
  size: 14
  normal:
    family: 'JetBrainsMonoNL Nerd Font Mono'

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux a -t 0 || tmux"

window:
  dimensions:
    columns: 185
    lines: 50
  decorations: full

cursor:
  style:
    shape: Underline
    blinking: Off

env:
  TERM: alacritty
