import = [
  "~/.config/alacritty/theme.toml"
]

[env]
TERM = "alacritty"

[font]
size = 12.7

[font.normal]
family = "JetBrainsMonoNL NFM"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
