import:
  - ~/.config/alacritty/theme.yml

font:
  size: 14
  normal:
    family: 'JetBrainsMonoNL Nerd Font Mono'

shell:
  program: /opt/homebrew/bin/fish

window:
  dimensions:
    columns: 100
    lines: 30
  decorations: full

cursor:
  style:
    shape: Underline
    blinking: Off

env:
  TERM: alacritty
