[cursor.style]
blinking = "Off"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 14

[font.normal]
family = "JetBrainsMonoNL NFM"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 120
lines = 40
