import:
  - ~/.config/alacritty/theme.yml

font:
  size: 14
  normal:
    family: 'JetBrainsMonoNL NFM'

shell:
  program: /opt/homebrew/bin/fish

window:
  dimensions:
    columns: 120
    lines: 40
  decorations: full
  decorations_theme_variant: Dark

cursor:
  style:
    shape: Underline
    blinking: Off

env:
  TERM: alacritty
