# 2023/04/02: テーマ設定は alacritty がメンテしている alacritty-theme を import する形に対応

import:
  - ~/.config/alacritty/themes/momiji.yaml

# フォント
font:
  size: 14
  normal:
    family: 'JetBrainsMonoNL Nerd Font Mono'

# シェルの設定
shell:
  ## 起動時に tmux を起動する
  program: /bin/zsh
  ## セッションが存在していればそのセッションに attach し、セッションが存在しない場合は新規セッションを作成する
  args:
    - -l
    - -c
    - "tmux a -t 0 || tmux"

# ウィンドウ設定
window:
  ## 起動時のウィンドウサイズを設定
  ## M2 MacBook Air (2,560 x 1,664) で Zoom 表示した際のサイズに合わせている (2023/03/07〜)
  dimensions:
    columns: 185
    lines: 50
  ## 起動時のウィンドウデコレーションを設定
  ## macOS では何も表示しないオプション等が用意されていたが今後 macOS 以外でも使う可能性を考慮して設定していない
  ## See also: https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L56-L65
  decorations: full

# セレクション設定
selection:
  ## Alacitty 上で指定した文字を自動的にクリップボードにコピーする
  ## tmux が pbcopy を叩きにいくのもありだけど、 pbcopy があるのは macOS だけなのでこれはあまり好まれない気がするので Alacitty にやらせたい
  save_to_clipboard: true

# カーソル設定
cursor:
  ## カーソルのスタイル設定
  style:
    shape: Underline
    ### カーソルの点滅を無効化
    blinking: Off

env:
  TERM: alacritty
