colors:
  primary:
    background: '0x09111A'
    foreground: '0xD9E6F2'

  cursor:
    text:   '0xD9E6F2'
    cursor: '0xD9E6F2'

  normal:
    black:   '0x000000'
    red:     '0xAC6D74'
    green:   '0x74AC6D'
    yellow:  '0xACA46D'
    blue:    '0x6D74AC'
    magenta: '0xA46DAC'
    cyan:    '0x6DACA4'
    white:   '0xE6E6E6'

  bright:
    black:   '0x262626'
    red:     '0xD6B8BC'
    green:   '0xBCD6B8'
    yellow:  '0xD6D3B8'
    blue:    '0xB8BCD6'
    magenta: '0xD3B8D6'
    cyan:    '0xB8D6D3'
    white:   '0xFFFFFF'
