font:
  size: 14
  normal:
    family: 'JetBrainsMonoNL NFM'

shell:
  program: /opt/homebrew/bin/fish

window:
  dimensions:
    columns: 120
    lines: 40
  decorations: full

colors:
  primary:
    background: '#191d19'
    foreground: '#d2d4de'

cursor:
  style:
    shape: Underline
    blinking: Off

env:
  TERM: alacritty
