import:
  - ~/.config/alacritty/theme.yml

font:
  size: 14
  normal:
    family: 'JetBrainsMonoNL NFM'

shell:
  program: /opt/homebrew/bin/fish
  args:
    - -l
    - -c
    - "tmux a -t 0 || tmux"

window:
  dimensions:
    columns: 120
    lines: 40
  decorations: full
  decorations_theme_variant: Dark

cursor:
  style:
    shape: Underline
    blinking: Off

env:
  TERM: alacritty
