format = '''
$directory$git_branch$hg_branch$fossil_branch$git_status$package$aws$buf$c$conda$dart$docker_context$elixir$elm$golang$guix_shell$haskell$haxe$java$julia$lua$meson$nim$nix_shell$nodejs$pijul_channel$python$rlang$ruby$rust$scala$spack$kotlin
[>>](#88C0D0) '''

[directory]
style = "#88C0D0"
read_only = " "

[git_branch]
style = "#88C0D0"
format = ": [$symbol$branch(:$remote_branch)]($style) "
symbol = " "

[git_status]
style = "#88C0D0"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[java]
style = "#e8688d"
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[kotlin]
symbol = "🅺 "

[deno]
symbol = "🦕 "
