import = [
    "~/.config/alacritty/theme.yml"
]

[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
dynamic_padding = true

[cursor.style]
shape = "Beam"
