import = [
    "~/.config/alacritty/theme.toml"
]

[env]
TERM = "alacritty"

[font]
size = 13.5

[font.normal]
family = "JetBrainsMonoNL NFM"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
dynamic_padding = true
# opacity = 0.8

[cursor]
blink_interval = 500

[cursor.style]
shape = "Beam"
blinking = "On"
