# import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "alacritty"

[font]
size = 13.5

[font.normal]
family = "JetBrainsMonoNL NFM"

[shell]
program = "/opt/homebrew/bin/fish"
# args = ["-l", "-c", "zellij attach --index 0 --create"]

[window]
decorations = "full"
dynamic_padding = true

[cursor.style]
shape = "Beam"
