import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "alacritty"

[font]
size = 13.5

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
dynamic_padding = true

[cursor.style]
shape = "Beam"
