import = [
  "~/.config/alacritty/theme.toml"
]

[env]
TERM = "alacritty"

[font]
size = 13.5

[font.normal]
family = "0xProto Nerd Font Mono"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
