[general]
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "JetBrainsMonoNL NFM"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[window]
opacity = 0.8
decorations = "buttonless"
padding = { x = 10, y = 10 }
dynamic_padding = true
blur = true

[cursor]
blink_interval = 500

[cursor.style]
shape = "Beam"
blinking = "Always"

[mouse]
hide_when_typing = true
