import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "alacritty"

[font]
size = 14

[font.normal]
family = "JetBrainsMonoNL NFM"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "full"
opacity = 0.8
dynamic_padding = true

[cursor.style]
shape = "Beam"
