[colors.primary]
background = '#0E131B'
foreground = '#C8D1DF'

[colors.cursor]
cursor = '#88abf9'

[colors.normal]
black   = '#6c8093'
red     = '#e16ba0'
green   = '#98c379'
yellow  = '#e8c37d'
blue    = '#7ecec6'
magenta = '#ba7bcc'
cyan    = '#53c6ba'
white   = '#c8d1df'

[colors.bright]
black   = '#8ba1b3'
red     = '#ff85b8'
green   = '#b0e78e'
yellow  = '#ffda93'
blue    = '#97ffeb'
magenta = '#d994e7'
cyan    = '#6dffd3'
white   = '#e3ecff'
