name: test

on:
  pull_request:
    branches:
      - main
    path:
      - 'runner.ts'
  push:
    branches:
      - main
    path:
      - 'runner.ts'

jobs:
  deploy-test:
    name: deploy dotfile test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: installer (link)
        run: deno task deploy

      - name: installer (exec)
        run: deno task setup
