name: test

on:
  pull_request:
    branches:
      - main
    path:
      - 'installer.ts'
  push:
    branches:
      - main
    path:
      - 'installer.ts'

jobs:
  test:
    name: test installer (macOS)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: installer
        run: ./installer.sh

